---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ishan-secret
spec: {}
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ishan-secret
  name: ishan-secret
  namespace: ishan-secret
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox:1.31.1
    name: ishan-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
data:
  pass: dGlnZXI=
  user: c2NvdHQ=
kind: Secret
metadata:
  creationTimestamp: null
  name: ishan-secret
  namespace: ishan-secret

