apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: netpol1
  name: netpol1
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: bookstore
  name: pod-b
  namespace: netpol1
spec:
  volumes:
  - emptyDir: {}
    name: vol1
  - emptyDir: {}
    name: vol2
  containers:
  - command:
    - /bin/sh
    - -c
    - sed -i 's/listen  .*/listen 1111;/g' /etc/nginx/conf.d/default.conf && exec
      nginx -g 'daemon off;'
    image: nginx
    volumeMounts:
    -  name: vol1
       mountPath: "/usr/share/nginx/html/"
    name: db-1
    ports:
    - containerPort: 1111
      protocol: TCP
  - command:
    - /bin/sh
    - -c
    - sed -i 's/listen  .*/listen 2222;/g' /etc/nginx/conf.d/default.conf && exec
      nginx -g 'daemon off;'
    image: nginx
    volumeMounts:
    -  name: vol2
       mountPath: "/usr/share/nginx/html/"
    name: db-2
    ports:
    - containerPort: 2222
      protocol: TCP
  initContainers:
  - name: init-myservice1
    image: busybox:1.28
    volumeMounts:
    -  name: vol1
       mountPath: "/data"
    command: ['sh', '-c', "echo 'database one: db - 1' > /data/index.html"]
  - name: init-myservice2
    image: busybox:1.28
    volumeMounts:
    -  name: vol2
       mountPath: "/data"
    command: ['sh', '-c', "echo 'database two : db - 2' > /data/index.html"]
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bookstore
  name: db1
  namespace: netpol1
spec:
  ports:
  - port: 1111
    protocol: TCP
    targetPort: 1111
  selector:
    app: bookstore
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bookstore
  name: db2
  namespace: netpol1
spec:
  ports:
  - port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    app: bookstore
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: coffeeshop
  name: pod-a
  namespace: netpol1
spec:
  containers:
  - image: nginx
    name: pod-a
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: client
  name: pod-c
  namespace: netpol1
spec:
  containers:
  - image: nginx
    name: pod-c
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

