apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: space1
  name: space1
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: space2
  name: space2
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: space3
  name: space3
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: db1
  name: db-1
  namespace: space2
spec:
  volumes:
  - emptyDir: {}
    name: vol1
  containers:
  - command:
    - /bin/sh
    - -c
    - sed -i 's/listen  .*/listen 1111;/g' /etc/nginx/conf.d/default.conf && exec
      nginx -g 'daemon off;'
    image: nginx
    volumeMounts:
    -  name: vol1
       mountPath: "/usr/share/nginx/html/"
    name: db-1
    ports:
    - containerPort: 1111
      protocol: TCP
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    volumeMounts:
    -  name: vol1
       mountPath: "/data"
    command: ['sh', '-c', "echo 'database one: db - 1' > /data/index.html"]
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: db2
  name: db-2
  namespace: space2
spec:
  volumes:
  - emptyDir: {}
    name: vol1
  containers:
  - command:
    - /bin/sh
    - -c
    - sed -i 's/listen  .*/listen 2222;/g' /etc/nginx/conf.d/default.conf && exec
      nginx -g 'daemon off;'
    image: nginx
    volumeMounts:
    -  name: vol1
       mountPath: "/usr/share/nginx/html/"
    name: db-2
    ports:
    - containerPort: 2222
      protocol: TCP
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    volumeMounts:
    -  name: vol1
       mountPath: "/data"
    command: ['sh', '-c', "echo 'database two : db - 2' > /data/index.html"]
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: backend
  name: backend
  namespace: space1
spec:
  containers:
  - image: nginx
    name: backend
    resources: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: vault3
  name: vault-3
  namespace: space3
spec:
  volumes:
  - emptyDir: {}
    name: vol1
  containers:
  - command:
    - /bin/sh
    - -c
    - sed -i 's/listen  .*/listen 3333;/g' /etc/nginx/conf.d/default.conf && exec
      nginx -g 'daemon off;'
    image: nginx
    volumeMounts:
    -  name: vol1
       mountPath: "/usr/share/nginx/html/"
    name: vault-3
    ports:
    - containerPort: 3333
      protocol: TCP
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    volumeMounts:
    -  name: vol1
       mountPath: "/data"
    command: ['sh', '-c', "echo 'vault secret -3 : vault - 3' > /data/index.html"]
